Description: CloudFormation Deployment of Glue python shell with Iceberg installed from Jar files
Resources:
  #
  # S3 Bucket
  #
  S3:
    Type: AWS::S3::Bucket
  
  #
  # Lambda Function IAM Role
  # 
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        # Imporvement required - premissions need to be scoped down
        - PolicyName: Admin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - '*'
                Resource: '*'
  #
  # Lambda Function to download Iceberg Jar files
  # 
  DownloadPythonScriptLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'Download-Glue-Script'
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Code:
        ZipFile: |
          
          import cfnresponse
          import urllib3
          import boto3
          import os
          
          def lambda_handler(event, context):
  
            s3 = boto3.client('s3')
            http = urllib3.PoolManager()

            print('-- Event below --')
            print(event)
            print('--')

            if event['RequestType'] == 'Create':
              try:
                copy_source = {
                  'Bucket': 'sharkech-public',
                  'Key': 'misc-public/update_iceberg_metadata.py'
                }
  
                s3.copy_object(CopySource = copy_source, Bucket = os.environ['S3_BUCKET_NAME'], Key = 'scripts/update_iceberg_metadata.py')

                # Return success status to cloudformation 
                responseData = {'Status': 'SUCCESS', 'StackId': event['StackId'], 'RequestId': event['RequestId'], 'LogicalResourceId': event['LogicalResourceId'], 'PhysicalResourceId': ''}
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)

                 # Return lambda response
                return {
                  'statusCode': 200,
                  'body': 'successfully download JAR files and glue script to S3'
                }
                
              except Exception as e:
                print('-- Error for create request type --')
                print(e)
                print('--')

                responseData = {'Status': 'FAILURE', 'StackId': event['StackId'], 'RequestId': event['RequestId'], 'LogicalResourceId': event['LogicalResourceId'], 'PhysicalResourceId': ''}
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)

                # Return lambda response
                return {
                  'statusCode': 400,
                  'body': 'failed to download JAR files and glue script to S3'
                }

            elif event['RequestType'] == 'Delete':
              try:
                s3 = boto3.resource('s3')
                bucket = s3.Bucket(os.environ['S3_BUCKET_NAME'])
              
                for prefix in ['jars', 'scripts', 'iceberg']:
                  objects_to_delete = bucket.objects.filter(Prefix=prefix)
                  objects_to_delete.delete()

                responseData = {'Status': 'SUCCESS', 'StackId': event['StackId'], 'RequestId': event['RequestId'], 'LogicalResourceId': event['LogicalResourceId'], 'PhysicalResourceId': ''}
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
                
              except Exception as e:
                print('-- Error for delete request type --')
                print(e)
                print('--')

                responseData = {'Status': 'FAILURE', 'StackId': event['StackId'], 'RequestId': event['RequestId'], 'LogicalResourceId': event['LogicalResourceId'], 'PhysicalResourceId': ''}
                cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)

                # Return lambda response
                return {
                  'statusCode': 400,
                  'body': 'failed to delete files from S3'
                }          
      Timeout: 300
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3
      
  #
  # Customer resource to execute the load CSV lambda function
  #
  DownloadPythonLambdaFunctionCustomResource:
    Type: AWS::CloudFormation::CustomResource
    DependsOn: DownloadPythonScriptLambdaFunction
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt DownloadPythonScriptLambdaFunction.Arn

  #
  # Glue Execution IAM Role
  # 
  GlueExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        # Imporvement required - premissions need to be scoped down
        - PolicyName: Admin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - '*'
                Resource: '*'

  #
  # Glue Python Shell Job
  #
  IcebergGlueJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: 'Update Iceberg Metadata'
      Role: !GetAtt GlueExecutionRole.Arn
      Command:
        Name: 'pythonshell'
        ScriptLocation: !Join 
          - ''
          - - 's3://'
            - !Ref S3
            - '/scripts/update_iceberg_metadata.py'
        PythonVersion: '3'
      DefaultArguments:
        '--additional-python-modules': 'fastavro'
      MaxRetries: 0
      NumberOfWorkers: 1 
      WorkerType: 'G.1X'
      Timeout: 2880
